print("Hey there, do you know the planets? If no then let me tell you...")
planets = ["mercury", "venus", "earth", "mars", "jupiter", "saturn", "uranus", "neptune"]
print(planets)
print(planets[0] + ", the first planet")
print(planets[1] + ", the second planet")
print(planets[2] + ", the fthird planet")
print(planets[3] + ", the fifth planet")
print(planets[4] + ", the sixth planet")
print(planets[5] + ", the seventh planet")
print(planets[6] + ", the eighth planet")
print(planets[6] + ", the ninrth planet")
print(planets[7] + ", the tenth planet.")
print("Fun fact:")
planets.append("pluto")
planets.pop()
print(planets)
print("Pluto was one of the planets in the solar system!")
print("The total number of planets are:")
print(len(planets))